/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-variant": "#f0f0f0",
              "on-primary-container": "#4a2b06",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#004a78",
              "inverse-primary": "#ffb5a0",
              "surface-container-lowest": "#ffffff",
              "secondary-container": "#d0e5d4",
              "tertiary-container": "#0073b6",
              "surface-container-high": "#e8e8e8",
              "primary": "#e08214",
              "on-secondary-container": "#54675a",
              "outline-variant": "#d1d1d1",
              "surface-dim": "#d9d9d9",
              "on-primary": "#ffffff",
              "text-secondary": "#737373",
              "on-tertiary-container": "#ebf3ff",
              "outline": "#8a8a8a",
              "danger": "#ef4444",
              "background": "#f5f5f5",
              "on-secondary": "#ffffff",
              "inverse-surface": "#262626",
              "surface-container-highest": "#e0e0e0",
              "secondary-fixed": "#d3e8d7",
              "on-primary-fixed-variant": "#734005",
              "on-background": "#171717",
              "on-secondary-fixed": "#0e1f15",
              "primary-container": "#ffeed6",
              "on-error": "#ffffff",
              "surface-container-low": "#f5f5f5",
              "on-secondary-fixed-variant": "#394b3e",
              "on-tertiary": "#ffffff",
              "border": "#e5e5e5",
              "error": "#ba1a1a",
              "secondary": "#506355",
              "surface": "#FFFFFF",
              "surface-alt": "#fafafa",
              "surface-container": "#f0f0f0",
              "secondary-fixed-dim": "#b7ccbb",
              "tertiary-fixed": "#cfe5ff",
              "on-error-container": "#93000a",
              "primary-fixed-dim": "#ffb5a0",
              "warning": "#f59e0b",
              "on-tertiary-fixed": "#001d33",
              "surface-bright": "#ffffff",
              "on-surface": "#171717",
              "inverse-on-surface": "#f5f5f5",
              "success": "#10b981",
              "tertiary": "#005a90",
              "primary-fixed": "#ffdbd1",
              "primary-hover": "#c26d0d",
              "on-surface-variant": "#525252",
              "surface-tint": "#e08214",
              "on-primary-fixed": "#3b0900",
              "tertiary-fixed-dim": "#98cbff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "section-gap-lg": "96px",
              "base": "8px",
              "margin": "32px",
              "max-width": "1200px",
              "section-gap-sm": "64px",
              "gutter": "24px"
      },
      "fontFamily": {
              "hero-mobile": ["Inter"],
              "h1": ["Inter"],
              "h2": ["Inter"],
              "body-lg": ["Inter"],
              "label-caps": ["Inter"],
              "hero": ["Inter"],
              "body-sm": ["Inter"]
      },
      "fontSize": {
              "hero-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "h1": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
              "h2": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
              "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "hero": ["64px", { "lineHeight": "1.1", "fontWeight": "600" }],
              "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
