/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "surface-variant": "#eae1d8",
              "on-primary-container": "#ffeeea",
              "error-container": "#ffdad6",
              "on-tertiary-fixed-variant": "#004a78",
              "inverse-primary": "#ffb5a0",
              "surface-container-lowest": "#ffffff",
              "secondary-container": "#d0e5d4",
              "tertiary-container": "#0073b6",
              "surface-container-high": "#f0e7de",
              "primary": "#9f2c05",
              "on-secondary-container": "#54675a",
              "outline-variant": "#e0bfb7",
              "surface-dim": "#e2d8d0",
              "on-primary": "#ffffff",
              "text-secondary": "#6B6259",
              "on-tertiary-container": "#ebf3ff",
              "outline": "#8c7169",
              "danger": "#B4432E",
              "background": "#FBF7F0",
              "on-secondary": "#ffffff",
              "inverse-surface": "#34302a",
              "surface-container-highest": "#eae1d8",
              "secondary-fixed": "#d3e8d7",
              "on-primary-fixed-variant": "#872100",
              "on-background": "#1f1b16",
              "on-secondary-fixed": "#0e1f15",
              "primary-container": "#c1441e",
              "on-error": "#ffffff",
              "surface-container-low": "#fcf2e9",
              "on-secondary-fixed-variant": "#394b3e",
              "on-tertiary": "#ffffff",
              "border": "#E5DDD0",
              "error": "#ba1a1a",
              "secondary": "#506355",
              "surface": "#FFFFFF",
              "surface-alt": "#F3ECE0",
              "surface-container": "#f6ece4",
              "secondary-fixed-dim": "#b7ccbb",
              "tertiary-fixed": "#cfe5ff",
              "on-error-container": "#93000a",
              "primary-fixed-dim": "#ffb5a0",
              "warning": "#D98E2B",
              "on-tertiary-fixed": "#001d33",
              "surface-bright": "#fff8f3",
              "on-surface": "#1f1b16",
              "inverse-on-surface": "#f9efe6",
              "success": "#4C7A5E",
              "tertiary": "#005a90",
              "primary-fixed": "#ffdbd1",
              "primary-hover": "#A63715",
              "on-surface-variant": "#59413b",
              "surface-tint": "#ab350f",
              "on-primary-fixed": "#3b0900",
              "tertiary-fixed-dim": "#98cbff"
      },
      "borderRadius": {
              "DEFAULT": "0.25rem",
              "lg": "0.5rem",
              "xl": "0.75rem",
              "full": "9999px"
      },
      "spacing": {
              "section-gap-lg": "96px",
              "base": "8px",
              "margin": "32px",
              "max-width": "1200px",
              "section-gap-sm": "64px",
              "gutter": "24px"
      },
      "fontFamily": {
              "hero-mobile": ["Newsreader"],
              "h1": ["Newsreader"],
              "h2": ["Newsreader"],
              "body-lg": ["Inter"],
              "label-caps": ["Inter"],
              "hero": ["Newsreader"],
              "body-sm": ["Inter"]
      },
      "fontSize": {
              "hero-mobile": ["40px", { "lineHeight": "1.2", "fontWeight": "600" }],
              "h1": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
              "h2": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
              "body-lg": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
              "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.05em", "fontWeight": "600" }],
              "hero": ["64px", { "lineHeight": "1.1", "fontWeight": "600" }],
              "body-sm": ["14px", { "lineHeight": "1.5", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
